dubbo:
  application:
    logger: slf4j
    name: file-service
    qos-port: 22229
  registry:
    address: nacos://mse-8dddf2f0-p.nacos-ans.mse.aliyuncs.com:8848
  protocol:
    name: dubbo
    port: 20887
  provider:
    timeout: 5000
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://8.217.40.165:3306/file_service
    username: root
    password: ${teamsphere_database}
    driver-class-name: com.mysql.cj.jdbc.Driver
