dubbo:
  application:
    logger: slf4j
    name: schedule-service
    qos-port: 22225
  registry:
    address: nacos://${nacos_address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20883
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://123.60.177.179:3306/file_service
    username: remote0
    password: ${mariadb}
    driver-class-name: org.mariadb.jdbc.Driver
