nacos:
  address: mse-5a242a20-p.nacos-ans.mse.aliyuncs.com
dubbo:
  application:
    logger: slf4j
    name: gateway-service
    qos-port: 22223
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20885
server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
