dubbo:
  application:
    logger: slf4j
    name: user-service
    qos-port: 22222
  registry:
    address: nacos://8.217.40.165:8848
  protocol:
    name: dubbo
    port: 20886
  provider:
    timeout: 5000
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://8.217.40.165:3306/user_service
    username: root
    password: ${teamsphere_database}
    driver-class-name: com.mysql.cj.jdbc.Driver
