dubbo:
  application:
    logger: slf4j
    name: user-service
    qos-port: 22222
  registry:
    address: nacos://${nacos_address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20886
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://123.60.177.179:3306/user_service
    username: remote0
    password: ${mariadb}
    driver-class-name: org.mariadb.jdbc.Driver
