nacos:
  address: mse-5a242a20-p.nacos-ans.mse.aliyuncs.com
dubbo:
  application:
    logger: slf4j
    name: user-service
    qos-port: 22222
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20886
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://8.217.40.165:3306/ts_test
    username: root
    password: ${ts_test_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
