dubbo:
  application:
    logger: slf4j
    name: member-service
    qos-port: 22226
  registry:
    address: nacos://8.217.40.165:8848
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 5000
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://8.217.40.165:3306/project_service
    username: root
    password: ${teamsphere_database}
    driver-class-name: com.mysql.cj.jdbc.Driver