dubbo:
  application:
    logger: slf4j
    name: member-service
    qos-port: 22226
  registry:
    address: nacos://${nacos_address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20880
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://123.60.177.179:3306/project_service
    username: remote0
    password: ${mariadb}
    driver-class-name: org.mariadb.jdbc.Driver