dubbo:
  application:
    logger: slf4j
    name: chat-service
    qos-port: 22228
  registry:
    address: nacos://${nacos_address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20882
server:
  port: 8085
spring:
  datasource:
    url: jdbc:mariadb://123.60.177.179:3306/chat_service
    username: remote0
    password: ${mariadb}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      host: 123.60.177.179
      port: 27017
      database: test
