dubbo:
  application:
    logger: slf4j
    name: chat-service
    qos-port: 22228
  registry:
    address: nacos://${nacos_address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20882
  provider:
    timeout: 5000
server:
  port: 8085
spring:
  datasource:
    url: jdbc:mariadb://123.60.177.179:3306/chat_service
    username: remote0
    password: ${mariadb}
    driver-class-name: org.mariadb.jdbc.Driver
