dubbo:
  application:
    logger: slf4j
    name: meeting-service
    qos-port: 22227
  registry:
    address: nacos://${nacos_address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 5000
server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://8.217.40.165:3306/meeting_service
    username: root
    password: ${teamsphere_database}
    driver-class-name: com.mysql.cj.jdbc.Driver
